### ISSUE TITLE
Sostituzione rete sentieristica Spina Verde (mappe google parchi)

### ISSUE THREAD

**Issue by danioxoli** [GISdevio/insubriparks_maps#1]
Sostituire nel branch [mappe_parchi](https://github.com/GISdevio/insubriparks_maps/tree/mappe_parchi) nella cartella dati delle [reti sentieristiche](https://github.com/GISdevio/insubriparks_maps/tree/mappe_parchi/public/reti_sentieristiche)
il geojson dei sentieri di Spina Verde (modifica a geometria del sentiero 12). Qui il geojson 
[parco_spina verde.zip](https://github.com/GISdevio/insubriparks_maps/files/13457452/parco_spina.verde.zip)

La mappa del portale che verrà cambiata [è questa:](https://insubriparksturismo.eu/parchi/7xfXeonyNJjJ3CIcUCRQ)

![immagine](https://github.com/GISdevio/insubriparks_maps/assets/15163569/78c3a7a9-a40e-4cfd-a074-cee5ae310a16)

Iniziamo a cambiare il codice in locale e poi passeremo il tutto a chi si occupa del portale.

**Comment by rizla93** [comment]
closed #b4db408
