### ISSUE TITLE
Update dati mappe_itineari

### ISSUE THREAD

**Issue by danioxoli** [GISdevio/insubriparks_maps#2]
Ciao @rizla93 ,

qui le modifiche per aggiornamento punti di interesse e relative foto nelle mappe degli itinerari sul portale (https://insubriparksturismo.eu/itinerari).

1) **Aggiornamento POI**
Sostituire il layer dei POI (vedi: https://github.com/GISdevio/insubriparks_maps/tree/mappe_itinerari/public/poi) con questo aggiornato. Il file è un GEOjson zippato, rinomina pure come è meglio per te quando carichi:  [sample_POI.zip](https://github.com/GISdevio/insubriparks_maps/files/14035957/sample_POI.zip)

2) **Aggiornamento foto** 
Aggiornare/sostituire la cartella immagini dei POI (https://github.com/GISdevio/insubriparks_maps/tree/mappe_itinerari/public/assets/img) con questa che include la revisione del materiale fotografico in accordo con aggiornamento dei POI: https://drive.google.com/file/d/1G_03ZNpnOLY1cOde8oHEGjYYzSXJMuJx/view?usp=sharing

Controlla che poi funzioni tutto e che la nominazione dei file (vedo qualche "." nel filename delle foto ecc..) non crei problemi. Nel caso segnalaci puntualmente che sistemiamo.

Quando hai finito ci mettiamo in contatto per aggiornamento del codice sul server del portale.

**Comment by rizla93** [comment]
closed #[53a6d4b](https://github.com/GISdevio/insubriparks_maps/commit/53a6d4bd580ecc191e33677018b18c190537700d)
