### ISSUE TITLE
Aggiornamento POI 2

### ISSUE THREAD

**Issue by danioxoli** [GISdevio/insubriparks_maps#3]
Ciao @rizla93 ,

qui le modifiche per aggiornamento punti di interesse delle mappe degli itinerari sul portale (https://insubriparksturismo.eu/itinerari).

Ci hanno chiesto delle piccole modifiche e ci sarebbe da ricaricare solamente il layer dei POI (vedi: https://github.com/GISdevio/insubriparks_maps/tree/mappe_itinerari/public/poi) con questo file (GEOjson zippato): [POI_v2.zip](https://github.com/GISdevio/insubriparks_maps/files/14236860/POI_v2.zip)

**Comment by rizla93** [comment]
Done [42d30f7](https://github.com/GISdevio/insubriparks_maps/commit/42d30f7b43d2033341b9d145b970fe1a4ef5683e)
